version: '3'
services:
  mysql:
    image: library/mysql:8.0.33
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d

  redis:
    hostname: redis
    container_name: redis
    image: redis:7.0.0
    command: redis-server --port 6379
    ports:
      - 6379:6379