version: '3'
services:
  bookbook2-db:
    image: library/mysql:8.0.33
    container_name: bookbook2-db
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64

  redis:
    hostname: redis
    container_name: redis
    image: redis:7.0.0
    command: redis-server --port 6379
    ports:
      - 6379:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
